# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@0.0.10

jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
workflows:
  runnning_test:
    jobs:
      - build-and-test
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
